<?php
/**
 *
 * This file is part of the GPMD Magento Responsive Theme.
 *
 * The GPMD Magento Responsive Theme is free software: you can redistribute
 * it and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * The GPMD Magento Responsive Theme is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with the GPMD Magento Responsive Theme. If not, see
 * http://www.gnu.org/licenses/.
 *
 * @category    GPMD
 * @package     GPMD_Responsive_Theme
 * @copyright   Copyright (c) 2012 GPMD.
 * @author      Matt Bailey @GPMD LTD
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<div class="message">
	<p>We have recently improved our system. Order history for all previous orders have now been archived and may not be readily available for viewing. If you need this information, please email us directly at custserv@numeonline.com with your full name, order number, and the email you placed your order with. Once we receive this information, we will process your request and email you a copy of your invoice in 1-3 business days.</p>
	<p>Thank you for being a Nume Customer!</p>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<div class="inner-shadow-wrapper">
	<table class="data-table" id="my-orders-table">
	    <col width="1" />
	    <col width="1" />
	    <col />
	    <col width="1" />
	    <col width="1" />
	    <col width="1" />
	    <thead>
	        <tr>
	            <th><?php echo $this->__('Order #') ?></th>
	            <th><?php echo $this->__('Date') ?></th>
	            <th><?php echo $this->__('Ship To') ?></th>
	            <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
	            <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
	        </tr>
	    </thead>
	    <tbody>
	        <?php $_odd = ''; ?>
	        <?php foreach ($_orders as $_order): ?>
	        <tr>
	            <td>
	            	<?php echo $_order->getRealOrderId() ?>
	            	<span style="font-size:80%" class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('[View]') ?></a>
	                    <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
	                    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
	                    <br/><a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('[Reorder]') ?></a>
	                <?php endif ?>
	                </span>
	            </td>
	            <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
	            <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
	            <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
	            <td><em><?php echo $_order->getStatusLabel() ?></em></td>
	        </tr>
	        <?php endforeach; ?>
	    </tbody>
	</table>
</div>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
