<div class="<?php echo $this->getContainerClassName()?>">
    <div class="two_fields">
        <div class="field1 name-firstname">
            <label for="<?php echo $this->getFieldId('firstname')?>" class="<?php echo $this->getFieldId('firstname')?>-invalid" title="first name required"><?php echo $this->__('First Name') ?></label>
            <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getFirstname()) ?>" title="<?php echo $this->__('First Name') ?>" />
        </div>
        <div class="field2 name-lastname">
            <label for="<?php echo $this->getFieldId('lastname')?>" class="<?php echo $this->getFieldId('lastname')?>-invalid" title="*last name required"><?php echo $this->__('Last Name') ?></label>
            <input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getLastname()) ?>" title="<?php echo $this->__('Last Name') ?>" />
        </div>
    </div>
</div>