<?php
$bestSellers = new Mage_Catalog_Block_Product_Bestseller;
$BestSellerIDs = $bestSellers->getBestSellersLast24Hours();
if (sizeof($BestSellerIDs) > 0): ?> 
<div class="section-title">
    <div class="linel"></div>
    <h2>Trending right <span class="brand-color">now</span></h2>
    <div class="liner"></div>
</div>
<?php $_collectionSize = count($BestSellerIDs) ?>
<div class="bestsellers">
<ul class="products-grid" id="products-grid-table">
<?php $i=1; foreach ($BestSellerIDs as $productids): $_product = Mage::getModel('catalog/product')->load($productids); ?>
<li>
    <span class="pro-img">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(200); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" /></a>
    </span>
    <p>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
    </p>
    <?php if($_product->getRatingSummary()): ?>
    <?php endif; ?>
    <?php if ($_product['special_price'] != NULL): ?>
        <span class="special-price">$<?php echo number_format($_product['special_price'], 2, '.', ','); ?></span>
        <span class="msrp">$<?php echo number_format($_product['price'], 2, '.', ','); ?> MSRP</span>
    <?php else: ?>
        <span class="price"><?php echo $this->getPriceHtml($_product, true) ?></span>
    <?php endif; ?>
    <?php if($_product->isSaleable()): ?>
        <button type="button" title="<?php echo $this->__('Shop') ?> <?php echo $this->__('Now') ?>" class="check-me-out-but" onclick="setLocation('<?php echo $_product->getProductUrl() //echo $this->getAddToCartUrl($_product) ?>')"><span><span><span class="pink"><?php echo $this->__('Shop') ?></span> <?php echo $this->__('Now') ?></span></span></button>
    <?php else: ?>
        <input type="button" name="" class="check-me-out-but" onclick="setLocation('<?php echo $_product->getProductUrl() //echo $this->getAddToCartUrl($_product) ?>')" value="<?php echo $this->__('Out Of Stock') ?>" />
    <?php endif; ?>
    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>

    <div class="line-accent"></div>
</li>

  <?php $i++; endforeach; $kol = $_collectionSize; ?>
</table>
<?php endif; ?>
</div>