	<div class="reviews-specs">
		<div class="container">
			<h3><a href="#">REVIEWS</a> / <a href="#">SPECS</a></h3>
			<div class="overall-bar">
				<div class="overall-left">
					OVERALL &nbsp;
					<span class="star-bar1">
						<a href="#">&nbsp;</a>
						<a href="#">&nbsp;</a>
						<a href="#">&nbsp;</a>
						<a href="#">&nbsp;</a>
						<a href="#">&nbsp;</a>
					</span>
					<ul>
						<li><a href="#">(8 Reviews)</a></li>
						<li><a href="#">Write a review</a></li>
					</ul>
				</div><!-- overall-left -->
				<div class="sort-link">
					<a href="#">SORT BY</a>
					<div class="select300">
						<select name="country_id" id="country_id" tabindex="1">
						<option value="">MOST RECENT</option>
						<option value="1">MOST RECENT 1</option>
						<option value="9">MOST RECENT 2</option>
						</select>
					</div><!-- select300 -->
				</div><!-- sort-link -->
			</div><!-- overall-bar -->
			<div class="reviews-block">
				<div class="review-post1">
					<div class="review-post-img"><img src="<?php echo $this->getSkinUrl('images/review-img1.jpg') ?>" alt="" /></div>
					<div class="review-post-data">
						<h6>DIANNA</h6>
							<span class="star-bar1">
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
							</span>
						<h5>SO HAPPY</h5>
						<span class="date-b">November 15, 2013</span>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt nisl ac urna pulvinar luctus. Sed faucibus mattis est a vehicula. Pellentesque aliquam nunc tellus. Lorem ipsum dolor sit amet, consectetur adi <a href="#">READ MORE</a></p>
					</div><!-- review-post-data -->
				</div><!-- review-post1 -->
				<div class="review-post1">
					<div class="review-post-img"><img src="<?php echo $this->getSkinUrl('images/review-img2.jpg') ?>" alt="" /></div>
						<div class="review-post-data">
							<h6>THEDAREBEAUTY</h6>
							<span class="star-bar1">
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
							</span>
							<h5>LOVE IT!</h5>
							<span class="date-b">November 15, 2013</span>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt nisl ac urna pulvinar luctus. Sed faucibus mattis est a. <a href="#">READ MORE</a></p>
						</div><!-- review-post-data -->
					</div><!-- review-post1 -->
				<div class="review-post1">
					<div class="review-post-img"><img src="<?php echo $this->getSkinUrl('images/review-img2.jpg') ?>" alt="" /></div>
						<div class="review-post-data">
							<h6>MB</h6>
							<span class="star-bar1">
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
							</span>
							<h5>IMPRESSIVE</h5>
							<span class="date-b">November 15, 2013</span>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt nisl ac urna pulvinar luctus. Sed faucibus mattis est a vehicula. Pellentesque aliquam nunc tellus. Lorem ipsum dolor sit. <a href="#">READ MORE</a></p>
						</div><!-- review-post-data -->
					</div><!-- review-post1 -->
				<div class="review-post1">
					<div class="review-post-img"><img src="<?php echo $this->getSkinUrl('images/review-img2.jpg') ?>" alt="" /></div>
						<div class="review-post-data">
							<h6>STEPH</h6>
								<span class="star-bar1">
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
								<a href="#">&nbsp;</a>
							</span>
							<h5>THE BEST WAND EVER</h5>
							<span class="date-b">November 15, 2013</span>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt nisl ac urna pulvinar luctus. Sed faucibus mattis est a vehicula. Pellentesque aliquam nunc tellus. Lorem ipsum dolor sit amet, consectetur adi <a href="#">READ MORE</a></p>
						</div><!-- review-post-data -->
					</div><!-- review-post1 -->
				<div class="more-review-but">
					<a href="#">MORE REVIEWS +</a> /
					<a href="#">WRITE A REVIEW <img src="<?php echo $this->getSkinUrl('images/heart-plus.png') ?>" alt="" /></a>
				</div><!-- more-review-but -->
			</div><!-- review-block -->
		</div><!-- container -->
	</div><!-- reviews-spec -->