
	<h2><span>&nbsp;</span><a href="#">ABOUT</a><a href="#">REVIEWS</a><a href="#" class="last">SIMILAR ITEMS</a><span>&nbsp;</span></h2>
	<div class="magic-wand-block container">
		<h3 class="sub-title3"><span></span>THE MAGIC WAND<span></span></h3>
		<div class="magic-deta1">
			<div class="pr-da pr-da1">
				<a href="<?php echo $this->getSkinUrl('images/color-img2.png') ?>"><strong>INNOVATIVE TECHNOLOGY</strong>
				<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tristique tellus ac feugiat aliquet. Maecenas eu cursus ipsum, ut elementum augue. Nam aliquam ac leo non tincidunt. Vestibulumtincidunt eu convallis sed, lobortis a odio.</span></a>
			</div>
			<div class="pr-da pr-da2">
				<a href="<?php echo $this->getSkinUrl('images/color-img3.png') ?>"><strong>ADJUSTABLE SETTINGS</strong>
				<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tristique tellus ac feugiat aliquet. Maecenas eu cursus ipsum, ut elementum augue. Nam aliquam ac leo non tincidunt. Vestibulumtincidunt eu  sed, convallis.</span></a>
			</div>
			<div class="pr-da pr-da3">
				<a href="<?php echo $this->getSkinUrl('images/color-img4.png') ?>"><strong>HAIR REPAIR</strong>
				<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tristique tellus ac feugiat aliquet. Maecenas eu cursus ipsum, ut elementum augue. Nam aliquam ac leo non tincidunt. Vestibulumtincidunt.</span></a>
			</div>
			<div class="pr-da pr-da1">
				<a href="<?php echo $this->getSkinUrl('images/color-img5.png') ?>"><strong>AN ENCHANTED MESSAGE</strong>
				<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tristique Nullam tristique tellus ac feugiat aliquet. Maecenas eu cursus ipsum, ut elementum augue. cidunt eu convallis sed, lobortis Nullam tristique Nullam tristique a odio.</span></a>
			</div>
		</div><!-- magic-deta1 -->
		<div class="magic-product">
			<ul class="pro-size">
				<li><a href="" class="mm19 size-ac">19 mm</a></li>
				<li><a href="" class="mm25 size-ac">25 mm</a></li>
			</ul>
			<span class="pro-img"><img src="<?php echo $this->getSkinUrl('images/color-img1.png') ?>" alt="" /></span>
			<button class="buy-now-but1">BUY NOW</button>
			<div class="button-box">
				<button>ADD TO CART</button>
				<button class="wish-list">WISH LIST</button>
				<button><img src="<?php echo $this->getSkinUrl('images/heart-plus.png') ?>" alt="" /> SHARE</button>
			</div>
			<ul class="pro-color">
				<li><a href="images/color-img1.png"><img src="<?php echo $this->getSkinUrl('images/pro-color1.png') ?>" alt="" /></a></li>
				<li><a href="images/color-img10.png"><img src="<?php echo $this->getSkinUrl('images/pro-color2.png') ?>" alt="" /></a></li>
				<li><a href="images/color-img11.png"><img src="<?php echo $this->getSkinUrl('images/pro-color3.png') ?>" alt="" /></a></li>
			</ul>
		</div><!-- magic-product -->
		<div class="magic-deta2">
			<div class="pr-da pr-da1">
				<a href="<?php echo $this->getSkinUrl('images/color-img6.png') ?>"><strong>INNOVATIVE TECHNOLOGY</strong>
				<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tristique tellus ac feugiat aliquet. Maecenas eu cursus ipsum, ut elementum augue. Nam aliquam ac leo non tincidunt. Vestibulumtincidunt eu convallis sed, lobortis a odio.</span></a>
			</div>
			<div class="pr-da pr-da2">
				<a href="<?php echo $this->getSkinUrl('images/color-img7.png') ?>"><strong>ADJUSTABLE SETTINGS</strong>
				<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tristique tellus ac feugiat aliquet. Maecenas eu cursus ipsum, ut elementum augue. Nam aliquam ac leo non tincidunt. Vestibulumtincidunt eu  sed, convallis.</span></a>
			</div>
			<div class="pr-da pr-da3">
				<a href="<?php echo $this->getSkinUrl('images/color-img8.png') ?>"><strong>HAIR REPAIR</strong>
				<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tristique tellus ac feugiat aliquet. Maecenas eu cursus ipsum, ut elementum augue. Nam aliquam ac leo non tincidunt. Vestibulumtincidunt.</span></a>
			</div>
			<div class="pr-da pr-da1">
				<a href="<?php echo $this->getSkinUrl('images/color-img9.png') ?>"><strong>AN ENCHANTED MESSAGE</strong>
				<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tristique Nullam tristique tellus ac feugiat aliquet. Maecenas eu cursus ipsum, ut elementum augue. cidunt eu convallis sed, lobortis Nullam tristique Nullam tristique a odio.</span></a>
			</div>
		</div><!-- magic-deta2 -->
	</div><!-- magic-wand-block container -->