<?php
/**
 *
 * This file is part of the GPMD Magento Responsive Theme.
 *
 * The GPMD Magento Responsive Theme is free software: you can redistribute
 * it and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * The GPMD Magento Responsive Theme is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with the GPMD Magento Responsive Theme. If not, see
 * http://www.gnu.org/licenses/.
 *
 * @category    GPMD
 * @package     GPMD_Responsive_Theme
 * @copyright   Copyright (c) 2012 GPMD.
 * @author      Matt Bailey @GPMD LTD
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php 
$_product = $this->getProduct();
//Zend_Debug::dump($_product->getCategory());
?>
<script type="text/javascript">
	var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-data-block container">
<div class="product-view">
	<div class="product-essential">
		<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
			<div class="product-col-left">
				<!-- <p class="product_zoom"> <img src=" <?php echo $this->getSkinUrl('images/zoom-icon.png'); ?> "/></p> -->
				<div class="pr-image-block">
					<?php echo $this->getChildHtml('media') ?>
				</div><!-- /pr-image-block -->
			</div><!-- /product-col-left -->
			<div class="pr-data-block">
				<div class="no-display">
					<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
					<input type="hidden" name="related_product" id="related-products-field" value="" />
				</div><!-- no-display -->
				<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
				<?php if ($_product->getCategory() != NULL): ?><span class="pr-sub-title"><?php echo $_product->getCategory()->getData('name'); ?></span><?php endif; ?>
				<?php if ($this->canEmailToFriend()): ?>
					<p><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
				<?php endif; ?>
				<div class="review-box">
					<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
				</div><!-- /review-box -->
				<?php if ($_product->getShortDescription()):?>
					<p class="product-description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
				<?php endif;?>
				<?php echo $this->getChildHtml('alert_urls') ?>
				<?php echo $this->getChildHtml('product_type_data') ?>
				<?php echo $this->getTierPriceHtml() ?>
				<?php echo $this->getChildHtml('extrahint') ?>
					<?php if (!$this->hasOptions()):?>
						<div class="add-to-box">
							<?php if($_product->isSaleable()): ?>
								<?php echo $this->getChildHtml('addtocart') ?>
								<?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
								<?php endif; ?>
							<?php endif; ?>
							<?php echo $this->getChildHtml('addto') ?>
						</div><!-- /add-to-box -->
						<?php echo $this->getChildHtml('extra_buttons') ?>
					<?php elseif (!$_product->isSaleable()): ?>
						<div class="add-to-box">
							<?php echo $this->getChildHtml('addto') ?>
						</div><!-- /add-to-box -->
					<?php endif; ?>
					<?php echo $this->getChildHtml('other');?>
					<?php if ($_product->isSaleable() && $this->hasOptions()):?>
						<!-- $this->getChildChildHtml('container1') -->
						<?php echo $this->getChildChildHtml('container1', '', true, true) ?><!-- $this->getChildChildHtml('container1') -->
					<?php endif;?>
				<?php if ($_product->isSaleable() && $this->hasOptions()):?>
					<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
				<?php endif;?>
			</div><!-- /pr-data-block -->
		</form>
	</div><!-- /product-essential -->
</div><!-- /product-view -->
	<script type="text/javascript">
	//<![CDATA[
			// please wait countdown start
			jQuery(document).ready(function(){
				jQuery('.buy-now1').on('popTime', function(){
					var countdown2 = 3;
					jQuery('.buy-now1 span').html('<span>Please Wait <span id="count">' + countdown2 + '</span></span>');
					var timer = setInterval(function() { 
					jQuery('#count').text(countdown2--);
						if (countdown2 == 0) {
							jQuery('#count').fadeOut('fast');
							clearInterval(timer);
						} 
					}, 1000);
				});
			});
		var productAddToCartForm = new VarienForm('product_addtocart_form');
		productAddToCartForm.submit = function(button, url) {
			if (this.validator.validate()) {
				var form = this.form;
				var oldUrl = form.action;
		//HummingbirdTracker.track({cart_add: true});
				jQuery('.buy-now1').trigger('popTime');
				// please wait countdown end
				if (url) {
				   form.action = url;
				}
				var e = null;
				try {
					this.form.submit();
				} catch (e) {
				}
				this.form.action = oldUrl;
				if (e) {
					throw e;
				}
				if (button && button != 'undefined') {
					button.disabled = true;
				}
			}
		}.bind(productAddToCartForm);
		productAddToCartForm.submitLight = function(button, url){
			if(this.validator) {
				var nv = Validation.methods;
				delete Validation.methods['required-entry'];
				delete Validation.methods['validate-one-required'];
				delete Validation.methods['validate-one-required-by-name'];
				if (this.validator.validate()) {
					if (url) {
						this.form.action = url;
					}
					this.form.submit();
				}
				Object.extend(Validation.methods, nv);
			}
		}.bind(productAddToCartForm);
	//]]>
	</script>
</div><!-- /product-data-block container -->
<div class="tag-block1">
	<?php //include ('tag-block.phtml'); ?>
	<?php echo $this->getChildHtml('product_additional_data') ?>
	<?php echo $this->getChildHtml('related-custom') ?>
</div><!-- tag-block1 -->