<?php if($this->getCurrencyCount() > 1): ?>
	<select onchange="window.location.href=this.value" name="custom-currency-selector" id="custom-currency-selector">
		<option selected="SELECTED"><?php echo $this->__('currency') ?></option>
		<?php foreach ($this->getCurrencies() as $_code => $_name): ?>
		<option value="<?php echo $this->getSwitchCurrencyUrl($_code)?>"
			<?php if($_code == $this->getCurrentCurrencyCode()): ?>
			<?php endif; ?>>
			<?php echo $_code ?>
		</option>
		<?php endforeach; ?>
	</select>
<?php endif; ?>