<script type="text/javascript">
//<![CDATA[
	var validateFields = [
			     "billing\\:company",
			     "billing\\:street1",
			     "billing\\:city",
			     "billing\\:postcode",
			];
    (function() {
	
        var magentoFields = [
                {
                    Company: "billing:company",
                    Line1: "billing:street1",
                    Line2: "billing:street2",
                    City: "billing:city",
                    State: "billing:region",
                    StateSelect: "billing:region_id",
                    Postcode: "billing:postcode",
                    CountrySelect: "billing:country_id" 
                },
                {
                    Company: "shipping:company",
                    Line1: "shipping:street1",
                    Line2: "shipping:street2",
                    City: "shipping:city",
                    State: "shipping:region",
                    StateSelect: "shipping:region_id",
                    Postcode: "shipping:postcode",
                    CountrySelect: "shipping:country_id"
                },
                {
                    Company: "company",
                    Line1: "street_1",
                    Line2: "street_2",
                    City: "city",
                    State: "region",
                    StateSelect: "region_id",
                    Postcode: "zip",
                    CountrySelect: "country"
                }
            ],
            key = '<?php echo Mage::getStoreConfig('captureplus/settings/website_key'); ?>',
            countryByIP = !!<?php echo Mage::getStoreConfig('captureplus/settings/ip_country'); ?>;
    
        function load(xyz) {
		if(xyz=="US"){
			validate_usps();
		}
		else{
		    function createAddressControl(addressFields) {
			var countryField = pca.getElement(addressFields.CountrySelect); 
			    magentoCountries = [];	
			
			for (var c = 0; c < countryField.options.length; c++)
			    magentoCountries.push(countryField.options[c].value);
		    
			var fields = [
			    { element: addressFields.Company, field: "Company", mode: pca.fieldMode.DEFAULT | pca.fieldMode.PRESERVE },
			    { element: addressFields.Line1, field: "Line1" },
			    { element: addressFields.Line2, field: "Line2", mode: pca.fieldMode.POPULATE },
			    { element: addressFields.City, field: "City", mode: pca.fieldMode.POPULATE },
			    { element: addressFields.State, field: "ProvinceName", mode: pca.fieldMode.POPULATE },
			    { element: addressFields.StateSelect, field: "ProvinceName", mode: pca.fieldMode.POPULATE },
			    { element: addressFields.Postcode, field: "PostalCode" },
			    { element: addressFields.CountrySelect, field: "CountryIso2", mode: pca.fieldMode.COUNTRY }
			],
			options = { 
			    key: key,
			    suppressAutocomplete: true,
			    countries: { 
				codesList: magentoCountries.join(","), 
				valueType: pca.countryNameType.ISO2 
			    },
			    source: "magento"
			},
			control = new pca.Address(fields, options);
		       
			//perform IP country lookup if required
			if (countryByIP)
			    control.setCountryByIP();
		    }
	    
		    for (var i = 0; i < magentoFields.length; i++) {
			if (pca.getElement(magentoFields[i].Line1)){
			    createAddressControl(magentoFields[i]);
			    }
		    }   
		}
        }
        
        
        jQuery( document ).ready(function() {
		alert('hello');
		var country_code = jQuery( "#billing\\:country_id" ).val();
		if(country_code == 'US'){
			validate_usps();
		}
		else{
			pca.fuzzyMatch = false;
			pca.ready(load);
		}
	});
	

	jQuery( "#billing\\:country_id" ).change(function() {
		var country_code = jQuery(this).val();
		if(country_code == 'US'){
			validate_usps();
			jQuery(".pcafooter").remove();
		}
		else{
			pca.fuzzyMatch = false;
			pca.ready(load);
			jQuery('#usps_address').hide();
		}
	});
	//validate_usps();

	jQuery( validateFields ).each(function( fld, element ) {
		jQuery('#' + element).on('blur', function(){
			validate_usps();
		});
	});

	jQuery('#billing-buttons-container').before('<div id="usps_address"></div>');

    })();


    function validate_usps(){
	  //alert('out us');
	  if(jQuery( "#billing\\:country_id" ).val() == 'US'){
	  //alert('in us');	 
	  jQuery('#usps_address').html('');
	  if(validateField()){
		   jQuery.ajax({
			url : "<?php echo $this->getUrl('captureplus/processing/usps') ?>",
			type: "POST",
			dataType: 'json',
			data :  {
				firm_name : jQuery('#billing\\:company').val(),
				address1: jQuery('#billing\\:street1').val(), 
				address2: jQuery('#billing\\:street2').val(), 
				city: jQuery('#billing\\:city').val(),  
				state: jQuery('#billing\\:region_id').find('option:selected').attr('title'), 
				zip: jQuery('#billing\\:postcode').val(),	
			},
			success: function(data, textStatus, jqXHR){
			        
				var str = '';
				if(data.Address.Error){
					jQuery('#usps_address').html(data.Address.Error.Description);
				}else if(data.Address){
					str = '<input type="radio" name="usps_address" id="usps_address">';
					if(data.Address.FirmName)
					str += 	data.Address.FirmName + ', ';
					if(data.Address.Address1)
					str += 	data.Address.Address1 + ', ';
					if(data.Address.Address2)
					str += 	data.Address.Address2 + ', ';
					if(data.Address.City)
					str += 	data.Address.City + ', ';
					if(data.Address.State)
					str += 	data.Address.State + ' ';
					if(data.Address.Zip5)
					str += 	data.Address.Zip5 + ' ';
				}
				jQuery('#usps_address').html(str);
			},
			error: function (jqXHR, textStatus, errorThrown) {

			}
			});
		   }
	   }else{
		jQuery('#usps_address').hide();
	   }
	}

	function validateField(){
		
		    validate = true;
		    jQuery( validateFields ).each(function( fld, element ) {
			if(jQuery('#' + element).val()==''){
				validate = false;
			}					
		    });
		    return validate ;
		    //return true;
	}
 
//]]>
</script>
