<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
	<div id="onepagecheckout_forgotbox" class='op_login_area' style="display: none;">
		<?php $forgot_url = $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on'))); ?>
		<?php $http_mode = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on'); ?>
		<?php if($http_mode) $forgot_url	= str_replace('http:', 'https:', $forgot_url); ?>
		<form action="<?php echo $forgot_url ?>" method="post" id="forgot-password-form" autocomplete="on">
			<div class="boxcontent form_fields">
				<p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
				<div class='full'>
					<div class="data_area">
						<input type="email" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" pattern="[^ @]*@[^ @]*" placeholder="E-mail" required value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
					</div>
				</div>
			</div>
			<div class="buttons-set">
					<button type="submit" title="<?php echo $this->__('Submit') ?>" id="btn-forgot" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
					<p class="back-link"><a href="javascript:void(0)" class="f-left onepagecheckout_loginlink clear"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
					<span class="please-wait" id="forgot-please-wait" style="display:none;">
							<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
					</span>
			</div>
		</form><!-- /forgot-password-form -->
		<script type="text/javascript">
		//<![CDATA[
				var forgotForm = new VarienForm('forgot-password-form', true);
		//]]>
		</script>
	</div>
<?php endif; ?>