<div class="onepagecheckout_block">
	<div class="form_fields">
		<div id="bill_form">
			<input type="hidden" name="billing[address_id]" id="form2address_id" value="167">
			<div class="customer-name">
				<div class="two_fields">
					<div class="field1 name-firstname">
						<label for="form2firstname" class="required">First Name</label>
						<input type="text" id="form2firstname" name="billing[firstname]" value="" title="First Name" class="t1 required-entry">
					</div>
					<div class="field2 name-lastname">
						<label for="form2lastname" class="required">Last Name</label>
						<input type="text" id="form2lastname" name="billing[lastname]" value="" title="Last Name" class="t1 required-entry">
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<div class="address-wrapper">
				<div class="address">
					<label for="form2street1" class="required">Address</label>
					<div class="data_area">
						<input type="text" title="Street Address" name="billing[street][]" id="form2street1" value="" class="t1 required-entry">
					</div>
				</div>
				<div class="suite">
					<div class="data_area">
						<input type="text" name="billing[street][]" id="form2street2" title="Street Address 2" value="" class="t1" placeholder="Apt. / Suite">
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<div class="two_fields"> 
				<div class="field1">
					<label class="valign-correct" for="form2country_id">Country</label>
					<div class="input-box-select">
						<select name="billing[country_id]" id="form2country_id" class="validate-select" title="Country">
							<option value=""> </option>
							<option value="AU">Australia</option>
							<option value="AT">Austria</option>
							<option value="AZ">Azerbaijan</option>
							<option value="BH">Bahrain</option>
							<option value="BE">Belgium</option>
							<option value="BG">Bulgaria</option>
							<option value="CA">Canada</option>
							<option value="DK">Denmark</option>
							<option value="FI">Finland</option>
							<option value="FR">France</option>
							<option value="DE">Germany</option>
							<option value="GR">Greece</option>
							<option value="GP">Guadeloupe</option>
							<option value="HK">Hong Kong SAR China</option>
							<option value="IS">Iceland</option>
							<option value="IN">India</option>
							<option value="ID">Indonesia</option>
							<option value="IE">Ireland</option>
							<option value="IL">Israel</option>
							<option value="IT">Italy</option>
							<option value="JP">Japan</option>
							<option value="KW">Kuwait</option>
							<option value="LU">Luxembourg</option>
							<option value="MT">Malta</option>
							<option value="MX">Mexico</option>
							<option value="NL">Netherlands</option>
							<option value="NO">Norway</option>
							<option value="SA">Saudi Arabia</option>
							<option value="SG">Singapore</option>
							<option value="SE">Sweden</option>
							<option value="CH">Switzerland</option>
							<option value="TH">Thailand</option>
							<option value="AE">United Arab Emirates</option>
							<option value="GB">United Kingdom</option>
							<option value="US" selected="selected">United States</option>
						</select>
					</div>
				</div>
				<div class="field2">
					<label for="form2postcode" class="required">Zip Code</label>
					<input type="text" title="Zip Code" name="billing[postcode]" id="form2postcode" value="" class="t1 validate-zip-international required-entry ">
				</div>
			</div>
			<div class="clear"></div>
			<div class="two_fields">
				<div class="field1">
					<label for="form2city" class="required">City</label>
					<input type="text" title="City" name="billing[city]" value="" class="t1 required-entry " id="form2city">
				</div>
				<div class="field2">
					<label class="valign-correct" for="form2region_id">State / Province</label>
					<div class="input-box-select">
						<select id="form2region_id" name="billing[region_id]" title="State / Province" class="validate-select required-entry" style="" defaultvalue="">
							<option value="">Select One</option>
							<option value="1" title="Alabama">Alabama</option>
							<option value="2" title="Alaska">Alaska</option>
							<option value="3" title="American Samoa">American Samoa</option>
							<option value="4" title="Arizona">Arizona</option>
							<option value="5" title="Arkansas">Arkansas</option>
							<option value="6" title="Armed Forces Africa">Armed Forces Africa</option>
							<option value="7" title="Armed Forces Americas">Armed Forces Americas</option>
							<option value="8" title="Armed Forces Canada">Armed Forces Canada</option>
							<option value="9" title="Armed Forces Europe">Armed Forces Europe</option>
							<option value="10" title="Armed Forces Middle East">Armed Forces Middle East</option>
							<option value="11" title="Armed Forces Pacific">Armed Forces Pacific</option>
							<option value="12" title="California">California</option>
							<option value="13" title="Colorado">Colorado</option>
							<option value="14" title="Connecticut">Connecticut</option>
							<option value="15" title="Delaware">Delaware</option>
							<option value="16" title="District of Columbia">District of Columbia</option>
							<option value="17" title="Federated States Of Micronesia">Federated States Of Micronesia</option>
							<option value="18" title="Florida">Florida</option>
							<option value="19" title="Georgia">Georgia</option>
							<option value="20" title="Guam">Guam</option>
							<option value="21" title="Hawaii">Hawaii</option>
							<option value="22" title="Idaho">Idaho</option>
							<option value="23" title="Illinois">Illinois</option>
							<option value="24" title="Indiana">Indiana</option>
							<option value="25" title="Iowa">Iowa</option>
							<option value="26" title="Kansas">Kansas</option>
							<option value="27" title="Kentucky">Kentucky</option>
							<option value="28" title="Louisiana">Louisiana</option>
							<option value="29" title="Maine">Maine</option>
							<option value="30" title="Marshall Islands">Marshall Islands</option>
							<option value="31" title="Maryland">Maryland</option>
							<option value="32" title="Massachusetts">Massachusetts</option>
							<option value="33" title="Michigan">Michigan</option>
							<option value="34" title="Minnesota">Minnesota</option>
							<option value="35" title="Mississippi">Mississippi</option>
							<option value="36" title="Missouri">Missouri</option>
							<option value="37" title="Montana">Montana</option>
							<option value="38" title="Nebraska">Nebraska</option>
							<option value="39" title="Nevada">Nevada</option>
							<option value="40" title="New Hampshire">New Hampshire</option>
							<option value="41" title="New Jersey">New Jersey</option>
							<option value="42" title="New Mexico">New Mexico</option>
							<option value="43" title="New York">New York</option>
							<option value="44" title="North Carolina">North Carolina</option>
							<option value="45" title="North Dakota">North Dakota</option>
							<option value="46" title="Northern Mariana Islands">Northern Mariana Islands</option>
							<option value="47" title="Ohio">Ohio</option>
							<option value="48" title="Oklahoma">Oklahoma</option>
							<option value="49" title="Oregon">Oregon</option>
							<option value="50" title="Palau">Palau</option>
							<option value="51" title="Pennsylvania">Pennsylvania</option>
							<option value="52" title="Puerto Rico">Puerto Rico</option>
							<option value="53" title="Rhode Island">Rhode Island</option>
							<option value="54" title="South Carolina">South Carolina</option>
							<option value="55" title="South Dakota">South Dakota</option>
							<option value="56" title="Tennessee">Tennessee</option>
							<option value="57" title="Texas">Texas</option>
							<option value="58" title="Utah">Utah</option>
							<option value="59" title="Vermont">Vermont</option>
							<option value="60" title="Virgin Islands">Virgin Islands</option>
							<option value="61" title="Virginia">Virginia</option>
							<option value="62" title="Washington">Washington</option>
							<option value="63" title="West Virginia">West Virginia</option>
							<option value="64" title="Wisconsin">Wisconsin</option>
							<option value="65" title="Wyoming">Wyoming</option>
						</select>
					</div>
					<script type="text/javascript">
					//<![CDATA[
						$('form2region_id').setAttribute('defaultValue',  "");
					//]]>
					</script>
					<input type="text" id="form2region" name="billing[region]" value="" title="State / Province" class="t1 required-entry" style="display: none;">
				</div>
			</div>
			<div class="clear"></div>
			<div class="two_fields">
				<div class="field1">
					<label for="form2telephone" class="required">Telephone</label>
					<input type="tel" pattern="[\+]\d{2}[\(]\d{2}[\)]\d{4}[\-]\d{4}" name="billing[telephone]" value="" title="Telephone" class="t1 required-entry " id="form2telephone">
				</div>
				<div class="field2">
					<label for="form2email" class="required">Email Address</label>
					<input type="text" name="billing[email]" value="" title="Email Address" class="t1 validate-email required-entry">
				</div>
			</div>
			<div class="clear"></div>
			<div class="two_fields" id="register-customer-password" style="display: none;">
				<div class="field1">
					<label for="form2customer_password" class="required">Password</label>
					<input type="password" name="billing[customer_password]" id="form2customer_password" title="Password" class="t1 required-entry validate-password">
				</div>
				<div class="field2">
					<label for="form2confirm_password" class="required">Confirm Password</label>
					<input type="password" name="billing[confirm_password]" title="Confirm Password" id="form2confirm_password" class="t1 required-entry validate-cpassword">
				</div>
			</div>
			<div class="clear"></div>
			<div>
				<div class="no-display">
					<input type="hidden" value="1" name="billing[save_in_address_book]">
				</div>
				<div class="options">
					<input type="checkbox" class="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1" checked="checked" title="Ship to this address" onclick="shipping.setSameAsBilling(this.checked)">
					<label>Ship to this address</label>
				</div>
			</div>
		</div>
		<input type="hidden" name="billing[use_for_shipping]" id="form2use_for_shipping" value="1">
	</div>
</div>
