<div id="ship_address_block" class="onepagecheckout_block">
	<div class="form_fields">
		<div id="ship_form">
			<input type="hidden" name="shipping[address_id]" id="form2shipping:address_id" value="168">
			<div class="two_fields">
				<div class="customer-name">
					<div class="two_fields">
						<div class="field1 name-firstname">
							<label for="form2shipping:firstname" class="required">First Name</label>
							<input type="text" id="form2shipping:firstname" name="shipping[firstname]" value="" title="First Name" class="t1 required-entry form2firstname" onchange="shipping.setSameAsBilling(false)">
						</div>
						<div class="field2 name-lastname">
							<label for="form2shipping:lastname" class="required">Last Name</label>
							<input type="text" id="form2shipping:lastname" name="shipping[lastname]" value="" title="Last Name" class="t1 required-entry form2lastname" onchange="shipping.setSameAsBilling(false)">
						</div>
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<div class="address-wrapper">
				<div class="address">
					<label>Address</label>
					<div class="data_area">
						<input type="text" title="Street Address" name="shipping[street][]" id="form2shipping:street1" value="" class="t1 required-entry" onchange="shipping.setSameAsBilling(false);">
					</div>
				</div>
				<div class="suite">
					<div class="data_area">
						<input type="text" name="shipping[street][]" id="form2shipping:street2" title="Street Address 2" value="" class="t1" onchange="shipping.setSameAsBilling(false);" placeholder="Apt. / Suite">
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<div class="two_fields">
				<div class="field1">
					<label class="valign-correct">Country</label>
					<div class="input-box-select">
						<select name="shipping[country_id]" id="form2shipping:country_id" class="validate-select" title="Country" onchange="shipping.setSameAsBilling(false);">
							<option value=""> </option>
							<option value="AU">Australia</option>
							<option value="AT">Austria</option>
							<option value="AZ">Azerbaijan</option>
							<option value="BH">Bahrain</option>
							<option value="BE">Belgium</option>
							<option value="BG">Bulgaria</option>
							<option value="CA">Canada</option>
							<option value="DK">Denmark</option>
							<option value="FI">Finland</option>
							<option value="FR">France</option>
							<option value="DE">Germany</option>
							<option value="GR">Greece</option>
							<option value="GP">Guadeloupe</option>
							<option value="HK">Hong Kong SAR China</option>
							<option value="IS">Iceland</option>
							<option value="IN">India</option>
							<option value="ID">Indonesia</option>
							<option value="IE">Ireland</option>
							<option value="IL">Israel</option>
							<option value="IT">Italy</option>
							<option value="JP">Japan</option>
							<option value="KW">Kuwait</option>
							<option value="LU">Luxembourg</option>
							<option value="MT">Malta</option>
							<option value="MX">Mexico</option>
							<option value="NL">Netherlands</option>
							<option value="NO">Norway</option>
							<option value="SA">Saudi Arabia</option>
							<option value="SG">Singapore</option>
							<option value="SE">Sweden</option>
							<option value="CH">Switzerland</option>
							<option value="TH">Thailand</option>
							<option value="AE">United Arab Emirates</option>
							<option value="GB">United Kingdom</option>
							<option value="US" selected="selected">United States</option>
						</select>
					</div>
				</div>
				<div class="field2">
					<label>Zip Code</label>
					<input type="text" name="shipping[postcode]" id="form2shipping:postcode" title="Zip Code" value="" class="t1 validate-zip-international required-entry " onchange="shipping.setSameAsBilling(false);">
				</div>
			</div>
			<div class="clear"></div>
			<div class="two_fields">
				<div class="field1">
					<label>City</label>
					<input type="text" name="shipping[city]" id="form2shipping:city" title="City" value="" class="t1 required-entry " onchange="shipping.setSameAsBilling(false);">
				</div>
			</div>
			<div class="clear"></div>
			<div class="two_fields">
				<div class="field1">
					<label>Telephone</label>
					<input type="tel" pattern="[\+]\d{2}[\(]\d{2}[\)]\d{4}[\-]\d{4}" name="shipping[telephone]" id="form2shipping:telephone" value="" title="Telephone" class="t1 required-entry " onchange="shipping.setSameAsBilling(false);">
				</div>
			</div>
			<div class="clear"></div>
			<div>
				<div class="no-display">
					<input type="hidden" name="shipping[save_in_address_book]" value="1">
				</div>
			</div>
		</div>
	</div>
</div>	
