<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.3.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="col2-set">
    <div class="col-1">
        <div class="inner-head">
            <h5>
                <?php echo $this->__('Contact Information') ?>
                <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('[Edit]') ?></a>
            </h5>
        </div>
        <p>
            <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
            <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('[Change Password]') ?></a>
        </p>
    </div>
    <?php if( Mage::helper('advancednewsletter')->extensionEnabled('AW_Advancednewsletter') ): ?>
    <div class="col-2">
        <div class="inner-head">
            <h5>
                <?php echo $this->__('Newsletters') ?>
                <a href="<?php echo $this->getUrl('advancednewsletter/manage') ?>"><?php echo $this->__('[Edit]') ?></a>
            </h5>
        </div>
        <p>
            <?php if( $this->getCustomerSegmentsTitles() ): ?>
                <?php echo $this->__("You are currently subscribed to ").$this->getCustomerSegmentsTitles() ?>
            <?php else: ?>
                <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
            <?php endif; ?>
        </p>
    </div>
    <?php endif; ?>
</div>
<br />
